- name: Tryhard Markers
  url: https://drive.google.com/file/d/15Eqex_HIO3B0Aga4qWL8kLc1vlVEIJ8e/view
  update_scheme: manual

- name: Fast Taco Markers
  url: https://fast.farming-community.eu/fast/markers/fast_TacO_pack.taco
  update_scheme: live_link

- name: Nekres' Hoard of Lost 'n Forgotten Markers
  url: https://github.com/agaertner/bhud-markers/releases/download/v0.0.2/Nekres.Markers.taco
  update_scheme: latest_github_release

- name: Tutle Point
  url: https://github.com/AsherGlick/TurtlePoint/releases/download/1.0/TurtlePoint.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/czokalapik/Czokalapik-s-Guides-for-GW2Taco/releases/download/v1.0.0/Czokalapik-s-Guides-for-GW2Taco.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/dlamkins/heart-zones/releases/download/2.0.1/HeartZones.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Emythiel/gw2-blish-markers/releases/download/v1.0.6/emysmarkers.zip
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Garfried/RACE-Beetle-Racing-Tracks/releases/download/v1.0/RACE_BeetleTracks.taco 
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Girbilcannon/Pewpews-Power-Paths/releases/download/v1.2.0/Pewpews_Power_Paths.taco
  upate_scheme: latest_github_release

- name: Zippy
  url: https://github.com/Girbilcannon/zippy/releases/download/Zippy1_8_0/Zippy.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/HeroineDark/HeroineDarks-Super-Adventure-Box-Guide/blob/main/HeroineDark%20SAB%20Guides.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/HeroineDark/HeroineDarks-Super-Adventure-Box-Guide/raw/main/HeroineDark%20SAB%20Guides.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Kaedalus/Mesmer-Fractal-Skips/releases/download/v1.0.2/MesmerFractalSkips.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/LadyElyssa/LadyElyssaTacoTrails/releases/download/v12.2/LadyElyssa.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Metallis/Metal-Marker-Myriad/releases/download/v7.3/Metal-Marker-Myriad.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Metallis/Only-Fish-Marker-Pack/releases/download/v1.10/Only-Fish.taco
  upate_scheme: latest_github_release

- name: Tyria Drift [DRFT] Racetracks
  url: https://github.com/n1nj44r91/Tyria-Drift-DRFT-GW2-TacO-Racetracks/releases/download/v3.1/DRFT_Main.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Nexrym/Nexploration/releases/download/v0.9.0/Nexploration.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/OlivierCharton/JapyxTrails/releases/download/1.1/JapyxTrails.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/placeholderwastakentwice/flooch-friendly-collection-routes/releases/download/V3/ffcr.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/QuitarHero/Heros-Marker-Pack/releases/download/v2.7.0/Hero.Blish.Pack.zip
  upate_scheme: latest_github_release

- name: Rediche's Siege Pack
  url: https://github.com/rediche/rediche-wvw-pack/releases/download/v1.0.8/RedicheWvwPack.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/Sutcenes/MovementOnTheWorld_TacoSupport/releases/download/31.05/MoW.taco
  upate_scheme: latest_github_release

- name: Twisted Castle Guide
  url: https://github.com/SZG5/gw2-twisted-castle/releases/download/0.4/TwistedCastle.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/xrandox/Automatic-Arrows/releases/download/v1.1.0/AutomaticArrows.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/xrandox/Tehs_Trails_MKL/releases/download/v1.2/TehsTrailsMKL.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/xrandox/TehsTrails-HeroPoints/releases/download/v1.0/TehsTrails-HeroPoints.taco
  upate_scheme: latest_github_release

- name: 
  url: https://github.com/xrandox/TehsTrails/releases/download/v5.2.0/TehsTrails.taco
  upate_scheme: latest_github_release

- name: 
  url: https://gitlab.com/lepaperwan/gw2-abaddon/-/jobs/2400738870/artifacts/raw/Abaddon.taco
  upate_scheme: latest_gitlab_release

- name: 
  url: https://moar-loot.web.app/releases/moar.taco
  update_scheme: live_link

- name: 
  url: https://www.heinze.fr/taco/download.php?f=3
  update_scheme: live_link

- name: 
  url: https://www.heinze.fr/taco/download.php?f=6
  update_scheme: live_link

- name: 
  url: https://www.tekkitsworkshop.net/download?download=1:tw-all-in-one
  update_scheme: live_link
