- https://drive.google.com/file/d/15Eqex_HIO3B0Aga4qWL8kLc1vlVEIJ8e/view
- https://fast.farming-community.eu/fast/markers/fast_TacO_pack.taco
- https://github.com/agaertner/bhud-markers/releases/download/v0.0.2/Nekres.Markers.taco
- https://github.com/AsherGlick/TurtlePoint/releases/download/1.0/TurtlePoint.taco
- https://github.com/czokalapik/Czokalapik-s-Guides-for-GW2Taco/releases/download/v1.0.0/Czokalapik-s-Guides-for-GW2Taco.taco
- https://github.com/dlamkins/heart-zones/releases/download/2.0.1/HeartZones.taco
- https://github.com/Emythiel/gw2-blish-markers/releases/download/v1.0.6/emysmarkers.zip
- https://github.com/Garfried/RACE-Beetle-Racing-Tracks/releases/download/v1.0/RACE_BeetleTracks.taco 
- https://github.com/Girbilcannon/Pewpews-Power-Paths/releases/download/v1.2.0/Pewpews_Power_Paths.taco
- https://github.com/Girbilcannon/zippy/releases/download/Zippy1_8_0/Zippy.taco
- https://github.com/HeroineDark/HeroineDarks-Super-Adventure-Box-Guide/blob/main/HeroineDark%20SAB%20Guides.taco
- https://github.com/HeroineDark/HeroineDarks-Super-Adventure-Box-Guide/raw/main/HeroineDark%20SAB%20Guides.taco
- https://github.com/Kaedalus/Mesmer-Fractal-Skips/releases/download/v1.0.2/MesmerFractalSkips.taco
- https://github.com/LadyElyssa/LadyElyssaTacoTrails/releases/download/v12.2/LadyElyssa.taco
- https://github.com/Metallis/Metal-Marker-Myriad/releases/download/v7.3/Metal-Marker-Myriad.taco
- https://github.com/Metallis/Only-Fish-Marker-Pack/releases/download/v1.10/Only-Fish.taco
- https://github.com/n1nj44r91/Tyria-Drift-DRFT-GW2-TacO-Racetracks/releases/download/v3.1/DRFT_Main.taco
- https://github.com/Nexrym/Nexploration/releases/download/v0.9.0/Nexploration.taco
- https://github.com/OlivierCharton/JapyxTrails/releases/download/1.1/JapyxTrails.taco
- https://github.com/placeholderwastakentwice/flooch-friendly-collection-routes/releases/download/V3/ffcr.taco
- https://github.com/QuitarHero/Heros-Marker-Pack/releases/download/v2.7.0/Hero.Blish.Pack.zip
- https://github.com/rediche/rediche-wvw-pack/releases/download/v1.0.8/RedicheWvwPack.taco
- https://github.com/Sutcenes/MovementOnTheWorld_TacoSupport/releases/download/31.05/MoW.taco
- https://github.com/SZG5/gw2-twisted-castle/releases/download/0.4/TwistedCastle.taco
- https://github.com/xrandox/Automatic-Arrows/releases/download/v1.1.0/AutomaticArrows.taco
- https://github.com/xrandox/Tehs_Trails_MKL/releases/download/v1.2/TehsTrailsMKL.taco
- https://github.com/xrandox/TehsTrails-HeroPoints/releases/download/v1.0/TehsTrails-HeroPoints.taco
- https://github.com/xrandox/TehsTrails/releases/download/v5.2.0/TehsTrails.taco
- https://gitlab.com/lepaperwan/gw2-abaddon/-/jobs/2400738870/artifacts/raw/Abaddon.taco
- https://moar-loot.web.app/releases/moar.taco
- https://www.heinze.fr/taco/download.php?f=3
- https://www.heinze.fr/taco/download.php?f=6
- https://www.tekkitsworkshop.net/download?download=1:tw-all-in-one