# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and generate web documents
        run: |
          cd burrito_converter
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          mkdir web_docs
          cd generators
          python3 main.py --documentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'burrito_converter/web_docs'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

